Rebuild for r-base 4.4 and UCRT mingw toolchain
conda-forge/r-rcppparallel-feedstock pull request #33
Opened 2024-08-20 13:48 UTC by WardBrian

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hi! I'm the maintainer for https://github.com/conda-forge/cmdstan-feedstock and a Windows user so I'm opening this PR to try a few things, as an alt to #30

2024-08-20 13:49 UTC, WardBrian commented
@conda-forge-admin, please rerender

2024-08-20 14:50 UTC, WardBrian commented
@conda-forge-admin, please rerender

2024-08-20 14:53 UTC, WardBrian commented
@mfansler since [b8d2609](https://github.com/conda-forge/r-rcppparallel-feedstock/pull/33/commits/b8d260993216580f83545a99622be523677df1a4) passed, I think this will work. It supersedes #30 #31 and #32


The main difference from #30 is that this does not try to unvendor TBB, due to the difficulties discussed in https://github.com/conda-forge/r-rcppparallel-feedstock/issues/29#issuecomment-2194695394, so it can also avoid using `r-clang`

I still think it would be nice to have something like a `tbb-mingw-feedstock` which could be built against the ABI R requires

2024-08-20 15:22 UTC, WardBrian commented
Ok, the migrator also set the non-x86 linux builds to cross compile on x86. I think this requires an `export arch=...` somewhere, but I'm not sure where is best to put it.

Alternatively, we could vendor TBB everywhere _except_ Windows, which is pretty easy to do

2024-08-20 15:24 UTC, WardBrian commented
@conda-forge-admin, please rerender

2024-08-20 15:44 UTC, WardBrian commented
@conda-forge-admin, please rerender

2024-08-22 06:02 UTC, jakirkham commented
cc @mfansler (for awareness)

2024-08-22 08:36 UTC, mfansler requested changes
Thanks for spending time with this @WardBrian! ❤️ 

I have some clarifying questions before merging.

2024-08-22 08:36 UTC, mfansler commented on recipe/meta.yaml
> +    - {{ compiler('cxx') }}
It is unclear to me that it is necessary to switch off the m2w64-based compilers for Windows. There were other (orthogonal) issues with the migration prior to when [@isuruf tried unvendoring tbb](https://github.com/conda-forge/r-rcppparallel-feedstock/pull/30/commits/99ccdfb2b5059732df1fa0e6cfa6c20330f15287) by adding `tbb-devel`. All my subsequent attempts at building kept the `tbb-devel`, so I wonder if just dropping that would be sufficient?

2024-08-22 08:36 UTC, mfansler commented on recipe/meta.yaml
> +    - arch=aarch64  # [aarch64]
I wonder why this asymmetrically impact `aarch64`? That is, shouldn't all the cross-compiles need this?

The logs show that the `ppc64le` arch for the `tbb` compilation is `arch=intel64`. Additionally, the `osx-arm64` builds show `arch=x86_64`. Since we don't actually test those builds, we are blind to whether it is actually usable.

I will turn on artifact retention so that I can native test the `osx-arm64` builds.

2024-08-22 08:39 UTC, mfansler commented
@conda-forge-admin please rerender

2024-08-22 09:21 UTC, mfansler commented on recipe/meta.yaml
> +    - arch=aarch64  # [aarch64]
I ran the unit tests manually on the **osx-arm64** R 4.4 artifact, with each backend (`tbb`, `tinythread`) and both passed without issue.

Since these tests are rather lightweight, I'm going to add them to the recipe. That would resolve this for me.

2024-08-22 09:31 UTC, mfansler commented
@conda-forge-admin please rerender

2024-08-22 12:47 UTC, WardBrian commented on recipe/meta.yaml
> +    - arch=aarch64  # [aarch64]
This arch flag primarily changes a few command line flag. It happens that PowerPC and arm64 can use the same flags as intel, but aarch64 can’t

2024-08-22 12:48 UTC, WardBrian commented on recipe/meta.yaml
> +    - {{ compiler('cxx') }}
This is still using the Mingw compilers, but it configures conda build such that compiler(“c”) just is mingw GCC in conda_build_config.yaml

2024-08-22 12:53 UTC, WardBrian commented on recipe/meta.yaml
> +    - {{ compiler('cxx') }}
In other words, this is primarily aesthetic, so if you prefer one way or the other both should be functional

2024-08-22 13:38 UTC, isuruf commented on recipe/meta.yaml
> +    - {{ compiler('cxx') }}
Let's keep `m2w64_c` here so that it's easier for the bot

2024-08-22 13:47 UTC, WardBrian commented
@conda-forge-admin, please rerender

2024-08-22 13:56 UTC, WardBrian commented on recipe/meta.yaml
> +    - {{ compiler('cxx') }}
Done

2024-08-22 14:46 UTC, mfansler approved these changes
LGTM. Thanks for answer my questions and fixing the test dependency!

2024-08-22 15:03 UTC, merged

2024-08-22 16:47 UTC, jakirkham commented
Thank you both! 🙏